services:
  mongo6:
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27019
      MONGO_COMMAND: 'mongosh'
    ports:
      - '27019:27019'
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'mongosh', 'admin', '--port', '27019', '--eval', "db.adminCommand('ping').ok" ]
      interval: 5s
      timeout: 2s
      retries: 20
