name: easylinks
services:
  mongo6:
    container_name: easylinks_mongo
    build:
      context: ./mongodb
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27022
      MONGO_COMMAND: 'mongosh'
    ports:
      - '27022:27022'
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'mongosh', 'admin', '--port', '27022', '--eval', "db.adminCommand('ping').ok" ]
      interval: 5s
      timeout: 2s
      retries: 20